# Generated by Django 4.2.3 on 2023-07-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
