# Generated by Django 4.2.3 on 2023-07-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_produtos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
