# Generated by Django 4.2.3 on 2023-07-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_produtos_descricao_alter_produtos_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='valor',
        ),
    ]
