# Generated by Django 4.2.3 on 2023-07-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_remove_produtos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='estoque',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
