# Generated by Django 4.2.3 on 2023-07-13 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_rename_carrinho_cliente_produtos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecom.cliente'),
        ),
    ]
